#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path : /
    controller: App\Controller\HomeController::index

game:
  path: /game
  controller: App\Controller\GamesController::index

register:
  path: /register
  controller: App\Controller\RegistrationController::registerAction

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

